'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import ServicesShowcase from '@/components/ServicesShowcase';
import ExperienceSection from '@/components/ExperienceSection';
import SalonAtmosphere from '@/components/SalonAtmosphere';
import TeamSection from '@/components/TeamSection';
import PricingSection from '@/components/PricingSection';
import ContactForm from '@/components/ContactForm';
import LocationSection from '@/components/LocationSection';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <ServicesShowcase />
        <ExperienceSection />
        <SalonAtmosphere />
        <TeamSection />
        <PricingSection />
        <ContactForm />
        <LocationSection />
        <Footer />
      </main>
    </>
  );
}